export enum Terrain {
  FOREST_CONIFEROUS = "FOREST_CONIFEROUS",
  FOREST_DECIDUOUS = "FOREST_DECIDUOUS",
  SAND = "SAND",
  WATER = "WATER"
}
export enum ForestFireState {
  NONE = "NONE",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  EXTREME = "EXTREME",
  DESTROYED = "DESTROYED"
}

